spring.application.name=feedback

# Database config
spring.datasource.url=jdbc:mysql://localhost:3306/feedback_app
spring.datasource.username=root
spring.datasource.password=MySql@26


#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Server 
server.port=8080
